language: sh
dist: focal
sudo: required

before_install:
  - sudo apt-get update

jobs:
  include:
  - stage: bucklescript
    script: |
      cd bs
      sudo apt-get install -y npm
      ./setup.sh
      ./build.sh

  - stage: ocaml
    script: |
      cd ocaml
      ./setup.sh
      bash -ex .travis-ocaml.sh
      opam switch create 4.11.0 && eval $(opam env) && sh setup-opam
      dune build src/dance.exe

  - stage: labltk
    script: |
      cd labltk
      ./setup.sh
      bash -ex .travis-ocaml.sh
      opam switch create 4.11.0 && eval $(opam env) && sh setup-opam
      dune build src/dance.exe

  - stage: lablgtk
    script: |
      cd lablgtk
      ./setup.sh
      bash -ex .travis-ocaml.sh
      opam switch create 4.11.0 && eval $(opam env) && sh setup-opam
      dune build src/dance.exe
      
  - stage: python
    script: |
      cd python
      ./setup.sh
      ./run.sh
      
  - stage: scalajs
    script: |
      cd scalajs
      sh setup.sh
      sbt fastOptJS

env:
  # only for ocaml
  - OCAML_VERSION=4.11
  - TRAVIS_DIST=focal
  
os:
  - linux
#  - osx
