language: c
sudo: required
before_install:
  - sudo apt-get update
  - sudo apt-get install nodejs
jobs:
  include:
  - stage: bucklescript
    script:
      - cd bs
      - npm i
      - ./build.sh
     
os:
  - linux
