language: c
sudo: required
before_install:
  - sudo apt-get update
  - sudo apt-get install nodejs make

  - cd ocaml
  - bash -ex .travis-ocaml.sh
  - eval $(opam env); sh setup-opam
  - cd ..
  
jobs:
  include:
  - stage: bucklescript
    script:
      - cd bs
      - npm i
      - ./build.sh
  - stage: ocaml
    script:
      - cd ocaml
      - make
#
env:
  # only for ocaml
  - OCAML_VERSION=4.02
os:
  - linux
