language: c
sudo: required
before_install:
  - sudo apt-get update

jobs:
  include:
  - stage: bucklescript
    script:
      - cd bs
      - sudo apt-get install nodejs make
      - npm i
      - ./build.sh
  - stage: ocaml
    script:
      - cd ocaml
      - sudo apt-get install make
      - bash -ex .travis-ocaml.sh
      - eval $(opam env); sh setup-opam
      - make
  - stage: scalajs
    script:
      - cd scalajs
      - echo "deb https://dl.bintray.com/sbt/debian /" | sudo tee -a /etc/apt/sources.list.d/sbt.list
      - curl -sL "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x2EE0EA64E40A89B84B2DF73499E82A75642AC823" | sudo apt-key add
      - sudo apt-get update
      - cat /etc/lsb-release
      - sudo apt search openjdk-11-jdk
      - sudo apt install sbt openjdk-11-jdk
      - sbt fastOptJS
#
env:
  # only for ocaml
  - OCAML_VERSION=4.02
os:
  - linux
