name: CI on macos

on: [push]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    - name: build bucklescript
      run: |
        cd bs
        ./setup.sh
        npm i
        ./build.sh
        mkdir site
        cp -r index.html js site

    - name: build python
      run: |
        cd python
        ./setup.sh
        ./run.sh

