name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: build bucklescript
      run: |
        cd bs
        sudo apt-get update
        sudo apt-get install -y nodejs make
        npm i
        ./build.sh
        mkdir site
        cp -r index.html js site
    - name: deploy bucklescript site
      uses: peaceiris/actions-gh-pages@v2
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./bs/site
    - name: build ocaml
      run: |
        cd ocaml
        sudo apt-get update
        sudo apt-get install -y make
        bash -ex .travis-ocaml.sh
        eval $(opam env)
        sh setup-opam
        make
      env:
        OCAML_VERSION: 4.02
        TRAVIS_OS_NAME: linux

    - name: build labltk
      run: |
        uname -a
        sudo apt-get update
        sudo apt-get install -y make
        bash -ex .travis-ocaml.sh
        eval $(opam env)
        sh setup-opam
        make
      env:
        OCAML_VERSION: 4.07.0
        TRAVIS_OS_NAME: linux
