name: CI on Linux

on: [push]

jobs:
  build_bucklescript:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: build bucklescript
      run: |
        cd bs
        sudo apt-get update
        sudo apt-get install -y nodejs make
        npm i
        ./build.sh
        mkdir site
        cp -r index.html js site

    - name: deploy bucklescript site
      uses: peaceiris/actions-gh-pages@v2
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./bs/site

  build_python:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: build python
      run: |
        cd python
        sudo apt-get update
        sudo apt-get install -y python3
        sh setup.sh
        sh run.sh

  build_ocaml:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: build ocaml
      run: |
        cd ocaml
        # sudo apt-get update
        # sudo apt-get install -y make
        bash -ex .travis-ocaml.sh
        eval $(opam env)
        sh setup-opam
        dune
      env:
        OCAML_VERSION: 4.11
        TRAVIS_OS_NAME: linux
        TRAVIS_DIST: focal

  build_labltk:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: build labltk
      run: |
        cd labltk
        bash -ex .travis-ocaml.sh
        eval $(opam env)
        ./setup.sh
        bash -x setup-opam
        dune
      env:
        OCAML_VERSION: 4.11
        TRAVIS_OS_NAME: linux
        TRAVIS_DIST: focal

  build_lablgtk:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: build lablgtk
      run: |
        cd lablgtk
        bash -ex .travis-ocaml.sh
        eval $(opam env)
        ./setup.sh
        sh setup-opam
        make
      env:
        OCAML_VERSION: 4.11
        TRAVIS_OS_NAME: linux
        TRAVIS_DIST: focal

  build_scalajs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: build scalajs
      run: |
        cd scalajs
        ./setup.sh
        sbt fastOptJS

  build_kotlinjs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: build kotlinjs
        run: |
          cd kotlinjs
          ./gradlew build

  build_haskell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install haskell
        uses: haskell/actions/setup@v1
        with:
          ghc-version: '8.10.4'
          cabal-version: '3.4.0.0'
      - name: build kotlinjs
        run: |
          cabal run
          ls -l dop.png

