name: CI on macos

on: [push]

jobs:
  build_bucklescript:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    - name: build bucklescript
      run: |
        cd bs
        ./setup.sh
        npm i
        ./build.sh
        mkdir site
        cp -r index.html js site

  build_python:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: build python
      run: |
        cd python
        ./setup.sh
        ./run.sh

  build_ocaml:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: build ocaml
      run: |
        cd ocaml
        bash -ex .travis-ocaml.sh
        eval $(opam env)
        sh setup-opam
        dune
      env:
        OPAM_VERSION: 2
        OCAML_VERSION: 4.11
        TRAVIS_OS_NAME: osx

  build_labltk:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: build labltk
      run: |
        cd labltk
        bash -ex .travis-ocaml.sh
        eval $(opam env)
        bash -x setup-opam
        dune
      env:
        OPAM_VERSION: 2
        OCAML_VERSION: 4.11
        TRAVIS_OS_NAME: osx

  build_lablgtk:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: build lablgtk
      run: |
        cd lablgtk
        bash -ex .travis-ocaml.sh
        eval $(opam env)
        sh setup-opam
        make
      env:
        OPAM_VERSION: 2
        OCAML_VERSION: 4.11
        TRAVIS_OS_NAME: osx

  build_scalajs:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: build scalajs
      run: |
        cd scalajs
        ./setup.sh
        sbt fastOptJS
