name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: build bucklescript
      run: |
        cd bs
        sudo apt-get update
        sudo apt-get install -y nodejs make
        npm i
        ./build.sh
        mkdir site
        cp -r index.html js site

    - name: build python
      run: |
        cd python
        sudo apt-get update
        sudo apt-get install -y python3
        sh setup.sh
        sh run.sh

    - name: build ocaml
      run: |
        cd ocaml
        sudo apt-get update
        sudo apt-get install -y make
        bash -ex .travis-ocaml.sh
        eval $(opam env)
        sh setup-opam
        make
      env:
        OCAML_VERSION: 4.02
        TRAVIS_OS_NAME: linux

    - name: build labltk
      run: |
        cd labltk
        sudo apt-get update
        sudo apt-get install -y make
        bash -ex .travis-ocaml.sh
        eval $(opam env)
        bash -x setup-opam
        make
      env:
        OCAML_VERSION: 4.07
        TRAVIS_OS_NAME: linux

    - name: build lablgtk
      run: |
        cd lablgtk
        sudo apt-get update
        sudo apt-get install -y make
        bash -ex .travis-ocaml.sh
        eval $(opam env)
        sh setup-opam
        make
      env:
        OCAML_VERSION: 4.07
        TRAVIS_OS_NAME: linux

    - name: build scalajs
      run: |
        cd scalajs
        ./setup.sh
        sbt fastOptJS
