name: mac_labltk

on: [push]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    - name: build labltk
      run: |
        cd labltk
        ./setup.sh
        bash -ex .travis-ocaml.sh
        eval $(opam env)
        bash -x setup-opam
        make
      env:
        OCAML_VERSION: 4.07
        TRAVIS_OS_NAME: osx
