name: CI on Linux

on: [push]

jobs:
  build_bucklescript:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: build bucklescript
      run: |
        cd bs
        sudo apt-get update
        sudo apt-get install -y nodejs make npm
        npm i
        ./build.sh
        mkdir site
        cp -r index.html js site

    - name: deploy bucklescript site
      uses: peaceiris/actions-gh-pages@v2
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./bs/site

  build_python:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: build python
      run: |
        cd python
        sudo apt-get update
        sudo apt-get install -y python3
        ./setup.sh
        sh run.sh

  build_ocaml:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: build ocaml
      run: |
        cd ocaml
        ls -la
        sudo apt update
        sudo apt install -y darcs unzip m4 make pkg-config
        bash -ex .travis-ocaml.sh
        eval $(opam env)
        ./setup.sh
        dune
        file dance
      env:
        OCAML_VERSION: 4.11
        TRAVIS_OS_NAME: linux
        TRAVIS_DIST: focal

  build_labltk:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: build labltk
      run: |
        cd labltk
        sudo apt update
        sudo apt install -y darcs unzip m4 make unzip
        bash -ex .travis-ocaml.sh
        eval $(opam env)
        ./setup.sh
        make
      env:
        OCAML_VERSION: 4.11
        TRAVIS_OS_NAME: linux
        TRAVIS_DIST: focal

  build_lablgtk:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: build lablgtk
      run: |
        cd lablgtk
        sudo apt update
        sudo apt install -y darcs make m4 unzip pkg-config
        bash -ex .travis-ocaml.sh
        eval $(opam env)
        ./setup.sh
        # dune build src/dance.exe
        make
        file dance
      env:
        OCAML_VERSION: 4.11
        TRAVIS_OS_NAME: linux
        TRAVIS_DIST: focal

  build_scalajs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: build scalajs
      run: |
        cd scalajs
        ./setup.sh
        sbt fastOptJS

  build_kotlinjs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: build kotlinjs
        run: |
          cd kotlinjs
          ./gradlew build

  build_haskell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install haskell
        uses: haskell/actions/setup@v1
        with:
          ghc-version: '8.10.4'
          cabal-version: '3.4.0.0'
      - name: build haskell
        run: |
          cd haskell
          bash setup.sh
          cabal run
          ls -l dop.png

  build_fortran:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install tools
        run: |
          sudo apt update
          sudo apt install -y gfortran libgtk-3-dev cmake libplplot-dev plplot-driver-cairo
          cd gtk-fortran
          git clone -b gtk3 https://github.com/vmagnin/gtk-fortran.git
          cd gtk-fortran
          mkdir build
          cd build
          cmake ..
          make
          sudo make install
          cd ../..
          ls -l
          make
          file dance

  build_rust:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: build rust
      run: |
        cd rust
        sudo apt-get update
        sudo apt-get install -y cargo
        # curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs > setup.sh
        # bash setup.sh -y
        # source $HOME/.cargo/env
        ./setup.sh
        cargo build
