name: CI on macos

on: [push]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    - name: build bucklescript
      run: |
        cd bs
        ./setup.sh
        npm i
        ./build.sh
        mkdir site
        cp -r index.html js site

    - name: deploy bucklescript site
      uses: peaceiris/actions-gh-pages@v2
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./bs/site

    - name: build python
      run: |
        cd python
        ./setup.sh
        ./run.sh

    - name: build ocaml
      run: |
        cd ocaml
        ./build.sh
        bash -ex .travis-ocaml.sh
        eval $(opam env)
        sh setup-opam
        make
      env:
        OCAML_VERSION: 4.02
        TRAVIS_OS_NAME: linux

    - name: build labltk
      run: |
        cd labltk
        brew install make
        bash -ex .travis-ocaml.sh
        eval $(opam env)
        bash -x setup-opam
        make
      env:
        OCAML_VERSION: 4.07
        TRAVIS_OS_NAME: linux

    - name: build lablgtk
      run: |
        cd lablgtk
        brew install make
        bash -ex .travis-ocaml.sh
        eval $(opam env)
        sh setup-opam
        make
      env:
        OCAML_VERSION: 4.07
        TRAVIS_OS_NAME: linux

    - name: build scalajs
      run: |
        cd scalajs
        ./setup.sh
        sbt fastOptJS

