name: macos_scalajs

on: [push]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    - name: build scalajs
      run: |
        cd scalajs
        ./setup.sh
        sbt fastOptJS
