name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: build bucklescript
      run: |
        cd bs
        sudo apt-get install nodejs make
        npm i
        ./build.sh
        cd ..        
    - name: build ocaml
      run: |
        cd 
        sudo apt-get install make
        bash -ex .travis-ocaml.sh
        eval $(opam env)
        sh setup-opam
        make
      env:
        OCAML_VERSION: 4.02
